name: Backend - Build & Push ECR

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.json'
      - '.github/workflows/back.yml'
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: mozartagentes-back-ecr
  IMAGE_TAG: latest

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file in root
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "✅ .env generado en la raíz"
          ls -la

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::534039229473:role/mozartagentes-gha-role

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 534039229473.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push 534039229473.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Force ECS service redeploy
        run: |
          aws ecs update-service \
            --cluster mozartagentes-cluster \
            --service mozartagentes-svc \
            --force-new-deployment \
            --region us-east-1
